// 20 realistic Nigerian deals used to populate the app on first run.
// Quality scores here are the *initial* seed values; they are recalculated
// by the scoring engine (src/services/scoringEngine.js) on every crawl pass
// and whenever a deal is voted on or verified, so they stay accurate.

const hoursFromNow = (h) => new Date(Date.now() + h * 3600 * 1000).toISOString();
const daysAgo = (d) => new Date(Date.now() - d * 24 * 3600 * 1000).toISOString();

// Builds a realistic 30-day price trail: it starts near `originalPrice`
// (or the deal price, if there's no original to compare against) and
// declines toward the current `dealPrice`, with small day-to-day jitter —
// so the scoring engine's 30/90-day average comparison reflects a genuine
// discount rather than averaging a flat line at the already-discounted price.
function history(originalPrice, dealPrice, days) {
  const start = originalPrice ?? dealPrice;
  const arr = [];
  for (let i = days; i >= 0; i -= 3) {
    const t = i / days;
    const base = dealPrice + (start - dealPrice) * t;
    const jitter = 1 + Math.sin(i) * 0.03;
    arr.push({ price: Math.max(0, Math.round(base * jitter)), date: daysAgo(i) });
  }
  return arr;
}

const RAW = [
  {
    brand: 'MTN Nigeria',
    brandLogo: '📶',
    title: '20GB Data for ₦3,500 — MTN Xtra Weekend Bonus',
    description:
      'Subscribe to the MTN Xtra Weekend plan and get 20GB of data valid for 7 days, usable anytime. Dial *312# to activate.',
    category: 'telecoms',
    imageUrl: 'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=800',
    dealUrl: 'https://www.mtn.ng/deal/',
    source: 'mtn',
    originalPrice: 6000,
    dealPrice: 3500,
    expiryHours: 5,
    createdDaysAgo: 0.2,
    upvotes: 214,
    downvotes: 6,
    stillWorksCount: 132,
    expiredCount: 2,
  },
  {
    brand: 'Jumia',
    brandLogo: '🛍️',
    title: 'Jumia Anniversary Sale — Up to 45% off Smartphones',
    description:
      'Flagship and mid-range smartphones from Samsung, Infinix, and Tecno discounted for the Jumia Anniversary Sale.',
    category: 'electronics',
    imageUrl: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800',
    dealUrl: 'https://www.jumia.com.ng/deals/',
    source: 'jumia',
    originalPrice: 185000,
    dealPrice: 101750,
    expiryHours: 30,
    createdDaysAgo: 1,
    upvotes: 341,
    downvotes: 18,
    stillWorksCount: 201,
    expiredCount: 2,
  },
  {
    brand: 'Chowdeck',
    brandLogo: '🍔',
    title: 'Free Delivery on Orders Above ₦5,000 This Weekend',
    description:
      'Chowdeck is waiving delivery fees on all food orders above ₦5,000 across Lagos, Abuja, and Port Harcourt this weekend.',
    category: 'food',
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800',
    dealUrl: 'https://chowdeck.com',
    source: 'chowdeck',
    originalPrice: 1500,
    dealPrice: 0,
    expiryHours: 48,
    createdDaysAgo: 0.5,
    upvotes: 189,
    downvotes: 24,
    stillWorksCount: 88,
    expiredCount: 2,
  },
  {
    brand: 'Shoprite Nigeria',
    brandLogo: '🛒',
    title: 'Buy 2 Get 1 Free on Household Essentials',
    description:
      'Selected household essentials — detergents, tissue paper, and toiletries — on a buy-2-get-1-free promo in-store.',
    category: 'supermarkets',
    imageUrl: 'https://images.unsplash.com/photo-1580913428023-02c429014861?w=800',
    dealUrl: 'https://www.shoprite.com.ng/',
    source: 'shoprite',
    originalPrice: 12000,
    dealPrice: 8000,
    expiryHours: 72,
    createdDaysAgo: 2,
    upvotes: 97,
    downvotes: 11,
    stillWorksCount: 54,
    expiredCount: 2,
  },
  {
    brand: 'Airtel Nigeria',
    brandLogo: '📡',
    title: 'SmartTRYBE: 10GB + Unlimited Night Data for ₦2,000',
    description:
      'Migrate to SmartTRYBE and enjoy 10GB day data plus unlimited night browsing (12am-5am) for 30 days.',
    category: 'telecoms',
    imageUrl: 'https://images.unsplash.com/photo-1580894732444-8ecded7900cd?w=800',
    dealUrl: 'https://www.airtel.com.ng/',
    source: 'airtel',
    originalPrice: 3500,
    dealPrice: 2000,
    expiryHours: 4,
    createdDaysAgo: 0.1,
    upvotes: 156,
    downvotes: 9,
    stillWorksCount: 101,
    expiredCount: 1,
  },
  {
    brand: 'Konga',
    brandLogo: '📦',
    title: 'Konga Yakata Sale — Kitchen Appliances from ₦8,500',
    description:
      'Blenders, kettles, and toasters slashed for the Konga Yakata flash sale. Limited stock, first come first served.',
    category: 'electronics',
    imageUrl: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800',
    dealUrl: 'https://www.konga.com/',
    source: 'konga',
    originalPrice: 15000,
    dealPrice: 8500,
    expiryHours: 20,
    createdDaysAgo: 0.8,
    upvotes: 122,
    downvotes: 14,
    stillWorksCount: 70,
    expiredCount: 2,
  },
  {
    brand: 'PalmPay',
    brandLogo: '💳',
    title: 'Refer & Earn ₦1,000 Instant Cashback',
    description:
      'Refer a friend to PalmPay and get an instant ₦1,000 cashback when they complete their first transaction.',
    category: 'banks',
    imageUrl: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800',
    dealUrl: 'https://www.palmpay.com/',
    source: 'palmpay',
    originalPrice: null,
    dealPrice: null,
    expiryHours: 96,
    createdDaysAgo: 3,
    upvotes: 88,
    downvotes: 5,
    stillWorksCount: 60,
    expiredCount: 2,
  },
  {
    brand: 'GTBank',
    brandLogo: '🏦',
    title: 'Zero COT on GTWorld Transfers This Month',
    description:
      'GTBank is waiving commission on turnover (COT) for all transfers made via the GTWorld app throughout the month.',
    category: 'banks',
    imageUrl: 'https://images.unsplash.com/photo-1541354329998-f4d9a9f9297f?w=800',
    dealUrl: 'https://www.gtbank.com/',
    source: 'gtbank',
    originalPrice: null,
    dealPrice: null,
    expiryHours: 200,
    createdDaysAgo: 5,
    upvotes: 64,
    downvotes: 8,
    stillWorksCount: 40,
    expiredCount: 2,
  },
  {
    brand: 'Jumia Fashion',
    brandLogo: '👗',
    title: 'Ankara Collection — Flat 30% Off Everything',
    description:
      'The full Ankara and Adire collection on Jumia Fashion is 30% off, including new arrivals from local designers.',
    category: 'fashion',
    imageUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800',
    dealUrl: 'https://www.jumia.com.ng/deals/',
    source: 'jumia',
    originalPrice: 25000,
    dealPrice: 17500,
    expiryHours: 60,
    createdDaysAgo: 1.5,
    upvotes: 143,
    downvotes: 19,
    stillWorksCount: 77,
    expiredCount: 2,
  },
  {
    brand: 'Bolt',
    brandLogo: '🚗',
    title: '50% Off Your Next 3 Bolt Rides',
    description:
      'Enjoy 50% off up to ₦1,000 on your next three Bolt rides within Lagos and Abuja. Applies automatically at checkout.',
    category: 'transport',
    imageUrl: 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=800',
    dealUrl: 'https://bolt.eu/en-ng/',
    source: 'bolt',
    originalPrice: 2000,
    dealPrice: 1000,
    expiryHours: 3,
    createdDaysAgo: 0.15,
    upvotes: 402,
    downvotes: 11,
    stillWorksCount: 260,
    expiredCount: 1,
  },
  {
    brand: 'Showmax',
    brandLogo: '🎬',
    title: '3 Months Showmax Pro for the Price of 1',
    description:
      'New subscribers get 3 months of Showmax Pro (with live sport) for the price of a single month — ₦2,900 total.',
    category: 'entertainment',
    imageUrl: 'https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?w=800',
    dealUrl: 'https://www.showmax.com/',
    source: 'showmax',
    originalPrice: 8700,
    dealPrice: 2900,
    expiryHours: 120,
    createdDaysAgo: 2.5,
    upvotes: 178,
    downvotes: 10,
    stillWorksCount: 99,
    expiredCount: 1,
  },
  {
    brand: 'Slot',
    brandLogo: '📱',
    title: 'iPhone 13 Refurbished — ₦420,000 (Was ₦510,000)',
    description: 'UK-used iPhone 13, 128GB, grade A refurbished units with 6 months warranty from Slot Systems.',
    category: 'electronics',
    imageUrl: 'https://images.unsplash.com/photo-1592286927505-1def25115481?w=800',
    dealUrl: 'https://www.slotnigeria.com/',
    source: 'generic',
    originalPrice: 510000,
    dealPrice: 420000,
    expiryHours: 80,
    createdDaysAgo: 3.2,
    upvotes: 61,
    downvotes: 13,
    stillWorksCount: 33,
    expiredCount: 2,
  },
  {
    brand: 'Domino’s Pizza',
    brandLogo: '🍕',
    title: 'Buy One Large Pizza, Get One Free — Tuesdays',
    description: 'Every Tuesday, buy any large pizza and get a second one of equal or lesser value absolutely free.',
    category: 'food',
    imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800',
    dealUrl: 'https://dominos.ng',
    source: 'generic',
    originalPrice: 9500,
    dealPrice: 4750,
    expiryHours: 14,
    createdDaysAgo: 0.6,
    upvotes: 233,
    downvotes: 15,
    stillWorksCount: 140,
    expiredCount: 1,
  },
  {
    brand: 'Kuda Bank',
    brandLogo: '🏧',
    title: 'Free ATM Withdrawals — First 3 This Month',
    description: 'Kuda customers get their first three ATM withdrawals fee-free every month, on any bank’s machine nationwide.',
    category: 'banks',
    imageUrl: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800',
    dealUrl: 'https://kuda.com',
    source: 'generic',
    originalPrice: null,
    dealPrice: null,
    expiryHours: 300,
    createdDaysAgo: 6,
    upvotes: 52,
    downvotes: 7,
    stillWorksCount: 30,
    expiredCount: 2,
  },
  {
    brand: 'Justrite',
    brandLogo: '🧺',
    title: 'Rice & Oil Combo Deal — Save ₦2,300',
    description: '10kg rice bundled with a 5-litre vegetable oil at a combined discount versus buying separately.',
    category: 'supermarkets',
    imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800',
    dealUrl: 'https://justriteshops.com',
    source: 'generic',
    originalPrice: 19800,
    dealPrice: 17500,
    expiryHours: 2.5,
    createdDaysAgo: 0.3,
    upvotes: 39,
    downvotes: 9,
    stillWorksCount: 21,
    expiredCount: 3,
  },
  {
    brand: '9mobile',
    brandLogo: '📞',
    title: 'WeekEnd Special: 15GB for ₦2,500',
    description: '9mobile subscribers can dial *200# to get 15GB of weekend-only data valid Friday 6pm to Sunday midnight.',
    category: 'telecoms',
    imageUrl: 'https://images.unsplash.com/photo-1512428813834-c702c7702b78?w=800',
    dealUrl: 'https://www.9mobile.com.ng/',
    source: 'generic',
    originalPrice: 4500,
    dealPrice: 2500,
    expiryHours: 5.5,
    createdDaysAgo: 0.25,
    upvotes: 111,
    downvotes: 8,
    stillWorksCount: 65,
    expiredCount: 2,
  },
  {
    brand: 'Zaron Cosmetics',
    brandLogo: '💄',
    title: 'Skincare Bundle — 3 for ₦9,000',
    description: 'Pick any three items from the Zaron skincare range — cleanser, toner, and moisturiser — bundled at a flat rate.',
    category: 'fashion',
    imageUrl: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800',
    dealUrl: 'https://zaroncosmetics.com',
    source: 'generic',
    originalPrice: 13500,
    dealPrice: 9000,
    expiryHours: 40,
    createdDaysAgo: 1.2,
    upvotes: 74,
    downvotes: 12,
    stillWorksCount: 41,
    expiredCount: 2,
  },
  {
    brand: 'inDrive',
    brandLogo: '🚕',
    title: 'Name Your Price — ₦500 Ride Credit for New Users',
    description: 'First-time inDrive users in Lagos get ₦500 ride credit automatically applied to their first negotiated fare.',
    category: 'transport',
    imageUrl: 'https://images.unsplash.com/photo-1517398013963-4735a4118dda?w=800',
    dealUrl: 'https://indrive.com',
    source: 'generic',
    originalPrice: 500,
    dealPrice: 0,
    expiryHours: 150,
    createdDaysAgo: 4,
    upvotes: 58,
    downvotes: 6,
    stillWorksCount: 35,
    expiredCount: 2,
  },
  {
    brand: 'Spotify',
    brandLogo: '🎧',
    title: 'Spotify Premium — 2 Months Free for Students',
    description: 'Verified students get two months of Spotify Premium free, then discounted pricing bundled with Showmax.',
    category: 'entertainment',
    imageUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800',
    dealUrl: 'https://www.spotify.com/ng/',
    source: 'generic',
    originalPrice: 1900,
    dealPrice: 0,
    expiryHours: 500,
    createdDaysAgo: 8,
    upvotes: 96,
    downvotes: 4,
    stillWorksCount: 58,
    expiredCount: 1,
  },
  {
    brand: 'Jumia Food',
    brandLogo: '🥡',
    title: '₦2,000 Off Orders Above ₦8,000',
    description: 'Use code JFOOD2K at checkout for ₦2,000 off any Jumia Food order above ₦8,000 from participating restaurants.',
    category: 'food',
    imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
    dealUrl: 'https://www.jumia.food/',
    source: 'jumia',
    originalPrice: 8000,
    dealPrice: 6000,
    expiryHours: 1.5,
    createdDaysAgo: 0.4,
    upvotes: 45,
    downvotes: 10,
    stillWorksCount: 24,
    expiredCount: 2,
  },
];

function seedDeals() {
  return RAW.map((d, i) => {
    const dealPrice = d.dealPrice;
    const savingsPercent =
      d.originalPrice && dealPrice != null && d.originalPrice > 0
        ? Math.round(((d.originalPrice - dealPrice) / d.originalPrice) * 100)
        : null;
    return {
      id: `d${i + 1}`,
      brand: d.brand,
      brandLogo: d.brandLogo,
      title: d.title,
      description: d.description,
      category: d.category,
      sourceCategory: null, // not produced by a Part 1 source — legacy seed data
      sourceId: null,
      imageUrl: d.imageUrl,
      dealUrl: d.dealUrl,
      originalPrice: d.originalPrice,
      dealPrice: d.dealPrice,
      savingsPercent,
      expiryDate: hoursFromNow(d.expiryHours),
      createdAt: daysAgo(d.createdDaysAgo),
      qualityScore: 50,
      priceHistory: dealPrice != null ? history(d.originalPrice, dealPrice, 30) : [],
      upvotes: d.upvotes,
      downvotes: d.downvotes,
      stillWorksCount: d.stillWorksCount,
      expiredCount: d.expiredCount,
      isVerified: d.stillWorksCount >= 10,
    };
  });
}

module.exports = { seedDeals };
